export type Tool = {
  slug: string;
  name: string;
  category: string;
  description: string;
  title: string;
  meta: string;
  formula?: string;
  inputs?: string[];
};

export const tools: Tool[] = [
  {slug:'gpa-calculator',name:'GPA Calculator',category:'Grades',description:'Estimate your semester or cumulative GPA with a simple student-friendly calculator.',title:'GPA Calculator for Students | StudentCalcHub',meta:'Free GPA calculator for students. Estimate semester GPA, cumulative GPA, and grade point averages quickly.',formula:'Add each course grade points multiplied by credit hours, then divide by total credit hours.',inputs:['Course credits','Grade points']},
  {slug:'final-grade-calculator',name:'Final Grade Calculator',category:'Grades',description:'Find what score you need on your final exam to reach your target class grade.',title:'Final Grade Calculator | What Score Do I Need?',meta:'Calculate the final exam score needed to reach your target grade. Free student final grade calculator.',formula:'Required final score = (target grade - current grade × remaining weight) / final exam weight.',inputs:['Current grade','Target grade','Final exam weight']},
  {slug:'weighted-grade-calculator',name:'Weighted Grade Calculator',category:'Grades',description:'Calculate your class average when assignments, quizzes, tests, and exams have different weights.',title:'Weighted Grade Calculator for Students',meta:'Free weighted grade calculator for students. Combine assignments, tests, quizzes, and final exams by category weight.',formula:'Multiply each category grade by its weight, then add the weighted results.',inputs:['Category grade','Category weight']},
  {slug:'grade-percentage-calculator',name:'Grade Percentage Calculator',category:'Grades',description:'Convert points earned into a percentage grade quickly.',title:'Grade Percentage Calculator | Points to Percent',meta:'Convert points earned and total points possible into a percentage grade with this free student calculator.',formula:'Grade percentage = points earned / total points × 100.',inputs:['Points earned','Total points']},
  {slug:'test-score-calculator',name:'Test Score Calculator',category:'Grades',description:'Turn correct answers into a percentage score and letter grade estimate.',title:'Test Score Calculator | StudentCalcHub',meta:'Calculate test scores from correct answers and total questions. Free test percentage calculator for students.',formula:'Test score = correct answers / total questions × 100.',inputs:['Correct answers','Total questions']},
  {slug:'assignment-grade-calculator',name:'Assignment Grade Calculator',category:'Grades',description:'Calculate your assignment grade from earned points and total points.',title:'Assignment Grade Calculator',meta:'Free assignment grade calculator for students. Convert assignment points into a percentage grade.',formula:'Assignment grade = earned points / possible points × 100.',inputs:['Earned points','Possible points']},
  {slug:'semester-grade-calculator',name:'Semester Grade Calculator',category:'Grades',description:'Estimate your semester grade using quarter, exam, and project grades.',title:'Semester Grade Calculator for Students',meta:'Estimate your semester class grade with this free student semester grade calculator.',formula:'Combine grading periods and exams according to their assigned weights.',inputs:['Quarter grades','Exam grade','Weights']},
  {slug:'class-average-calculator',name:'Class Average Calculator',category:'Grades',description:'Find the average of multiple test, quiz, or assignment scores.',title:'Class Average Calculator',meta:'Calculate the average of class grades, quiz scores, homework grades, or test scores.',formula:'Average = sum of scores / number of scores.',inputs:['Scores']},
  {slug:'letter-grade-calculator',name:'Letter Grade Calculator',category:'Grades',description:'Convert a percentage score into a common letter grade estimate.',title:'Letter Grade Calculator | Percentage to Letter Grade',meta:'Convert percentage grades into letter grades with this free student grade calculator.',formula:'Compare your percentage to a typical grading scale.',inputs:['Percentage']},
  {slug:'grade-improvement-calculator',name:'Grade Improvement Calculator',category:'Grades',description:'Estimate how much your grade could improve after a new assignment or exam.',title:'Grade Improvement Calculator',meta:'Estimate how a future assignment, test, or exam may improve your class grade.',formula:'New grade = current grade × current weight + new score × new weight.',inputs:['Current grade','New score','New weight']},

  {slug:'study-time-calculator',name:'Study Time Calculator',category:'Study Planning',description:'Plan how many study hours you need before a test, exam, or project deadline.',title:'Study Time Calculator for Students',meta:'Plan study hours before an exam or deadline with this free study time calculator.',formula:'Study time per day = total study hours needed / days available.',inputs:['Study hours needed','Days available']},
  {slug:'homework-time-calculator',name:'Homework Time Calculator',category:'Study Planning',description:'Estimate how long your homework load will take based on assignments and pace.',title:'Homework Time Calculator',meta:'Estimate homework time and plan your evening study schedule with this student calculator.',formula:'Total time = sum of estimated time for each assignment.',inputs:['Assignment count','Minutes per assignment']},
  {slug:'reading-time-calculator',name:'Reading Time Calculator',category:'Study Planning',description:'Estimate how long a chapter, article, or reading assignment will take.',title:'Reading Time Calculator for Students',meta:'Calculate reading time for textbook chapters, articles, essays, and assignments.',formula:'Reading time = total words / words read per minute.',inputs:['Word count','Reading speed']},
  {slug:'essay-word-count-calculator',name:'Essay Word Count Calculator',category:'Writing',description:'Estimate pages, paragraphs, and reading time from an essay word count.',title:'Essay Word Count Calculator',meta:'Estimate essay pages, paragraphs, and reading time from word count.',formula:'Pages = word count / words per page.',inputs:['Word count','Words per page']},
  {slug:'essay-page-calculator',name:'Essay Page Calculator',category:'Writing',description:'Convert essay word count into estimated pages for common formatting.',title:'Essay Page Calculator | Words to Pages',meta:'Convert essay word count to pages for double-spaced or single-spaced school assignments.',formula:'Estimated pages depend on spacing, font size, and words per page.',inputs:['Word count','Spacing']},
  {slug:'citation-count-calculator',name:'Citation Count Calculator',category:'Writing',description:'Estimate how many sources you may need for a research paper.',title:'Citation Count Calculator for Research Papers',meta:'Estimate a reasonable citation count for essays and research papers by length and assignment type.',formula:'A common estimate is one source per 250 to 500 words, adjusted by assignment type.',inputs:['Word count','Citation density']},
  {slug:'flashcard-time-calculator',name:'Flashcard Time Calculator',category:'Study Planning',description:'Estimate how long it will take to review a stack of flashcards.',title:'Flashcard Time Calculator',meta:'Calculate flashcard review time based on card count and seconds per card.',formula:'Review time = number of cards × seconds per card.',inputs:['Cards','Seconds per card']},
  {slug:'pomodoro-calculator',name:'Pomodoro Calculator',category:'Study Planning',description:'Plan Pomodoro study sessions and breaks for focused schoolwork.',title:'Pomodoro Calculator for Students',meta:'Plan Pomodoro sessions, study blocks, and breaks with this free calculator for students.',formula:'Total time = focus sessions + short breaks + long breaks.',inputs:['Sessions','Focus minutes','Break minutes']},
  {slug:'exam-countdown-calculator',name:'Exam Countdown Calculator',category:'Study Planning',description:'Count days until an upcoming exam and plan study sessions.',title:'Exam Countdown Calculator',meta:'Calculate how many days are left until your exam and plan your study schedule.',formula:'Days remaining = exam date - today.',inputs:['Exam date']},
  {slug:'deadline-countdown-calculator',name:'Deadline Countdown Calculator',category:'Study Planning',description:'Count how many days are left before a paper, project, or assignment deadline.',title:'Deadline Countdown Calculator',meta:'Free deadline countdown calculator for assignments, papers, projects, and exams.',formula:'Days remaining = deadline date - today.',inputs:['Deadline date']},

  {slug:'tuition-calculator',name:'Tuition Calculator',category:'College Money',description:'Estimate tuition cost from credit hours and cost per credit.',title:'Tuition Calculator | Cost Per Credit Hour',meta:'Estimate tuition by credit hours and cost per credit with this free student tuition calculator.',formula:'Tuition = credit hours × cost per credit hour.',inputs:['Credit hours','Cost per credit']},
  {slug:'college-cost-calculator',name:'College Cost Calculator',category:'College Money',description:'Estimate total college costs including tuition, fees, books, housing, and supplies.',title:'College Cost Calculator',meta:'Estimate total college costs including tuition, fees, books, housing, and supplies.',formula:'Total cost = tuition + fees + books + housing + other expenses.',inputs:['Tuition','Fees','Books','Housing']},
  {slug:'student-loan-payment-calculator',name:'Student Loan Payment Calculator',category:'College Money',description:'Estimate monthly student loan payments from balance, rate, and term.',title:'Student Loan Payment Calculator',meta:'Estimate monthly student loan payments with this free calculator for students and graduates.',formula:'Payment depends on loan amount, interest rate, and repayment term.',inputs:['Loan amount','Interest rate','Years']},
  {slug:'scholarship-savings-calculator',name:'Scholarship Savings Calculator',category:'College Money',description:'See how much a scholarship reduces your school cost.',title:'Scholarship Savings Calculator',meta:'Calculate how scholarships reduce tuition and total college costs.',formula:'Remaining cost = total cost - scholarship amount.',inputs:['Total cost','Scholarship amount']},
  {slug:'textbook-cost-calculator',name:'Textbook Cost Calculator',category:'College Money',description:'Estimate textbook and supply costs for a semester.',title:'Textbook Cost Calculator',meta:'Estimate textbook costs for a semester based on number of classes and average book cost.',formula:'Textbook cost = number of classes × average cost per class.',inputs:['Classes','Average textbook cost']},
  {slug:'college-budget-calculator',name:'College Budget Calculator',category:'College Money',description:'Plan a monthly student budget for rent, food, books, transportation, and personal expenses.',title:'College Budget Calculator for Students',meta:'Build a monthly college budget with categories for housing, food, books, transportation, and more.',formula:'Monthly budget = sum of planned spending categories.',inputs:['Income','Expenses']},

  {slug:'attendance-percentage-calculator',name:'Attendance Percentage Calculator',category:'School Life',description:'Calculate your attendance percentage from attended and total classes.',title:'Attendance Percentage Calculator',meta:'Calculate school or class attendance percentage from attended classes and total classes.',formula:'Attendance percentage = attended classes / total classes × 100.',inputs:['Attended classes','Total classes']},
  {slug:'absence-calculator',name:'Absence Calculator',category:'School Life',description:'Estimate how many classes you can miss while keeping a target attendance percentage.',title:'Absence Calculator for Students',meta:'Find how many classes you can miss while keeping your required attendance percentage.',formula:'Allowed absences depend on total classes and required attendance percentage.',inputs:['Total classes','Required attendance']},
  {slug:'course-load-calculator',name:'Course Load Calculator',category:'School Life',description:'Estimate weekly workload based on credit hours and study expectations.',title:'Course Load Calculator',meta:'Estimate weekly college workload from credit hours and study time per credit.',formula:'Weekly workload = class hours + study hours per credit.',inputs:['Credit hours','Study hours per credit']},
  {slug:'credit-hour-calculator',name:'Credit Hour Calculator',category:'School Life',description:'Estimate total credit hours for a semester or degree plan.',title:'Credit Hour Calculator',meta:'Add up credit hours for courses, semesters, or degree planning.',formula:'Total credit hours = sum of course credit hours.',inputs:['Course credits']},
  {slug:'graduation-year-calculator',name:'Graduation Year Calculator',category:'School Life',description:'Estimate your graduation year based on current year and years remaining.',title:'Graduation Year Calculator',meta:'Estimate expected graduation year for high school or college students.',formula:'Graduation year = current year + years remaining.',inputs:['Current year','Years remaining']},
  {slug:'age-at-graduation-calculator',name:'Age at Graduation Calculator',category:'School Life',description:'Estimate how old you will be when you graduate.',title:'Age at Graduation Calculator',meta:'Calculate estimated age at graduation based on birth year and graduation year.',formula:'Age at graduation = graduation year - birth year.',inputs:['Birth year','Graduation year']},

  {slug:'percentage-calculator-for-students',name:'Percentage Calculator for Students',category:'Math Help',description:'Solve common student percentage problems quickly.',title:'Percentage Calculator for Students',meta:'Free student percentage calculator for grades, scores, discounts, and math homework.',formula:'Percentage = part / whole × 100.',inputs:['Part','Whole']},
  {slug:'ratio-calculator',name:'Ratio Calculator',category:'Math Help',description:'Simplify ratios and compare quantities for math homework.',title:'Ratio Calculator',meta:'Simplify ratios and compare quantities with this free student ratio calculator.',formula:'Divide both parts of a ratio by their greatest common factor.',inputs:['First number','Second number']},
  {slug:'average-calculator',name:'Average Calculator',category:'Math Help',description:'Calculate the average of numbers for grades, data sets, and homework.',title:'Average Calculator for Students',meta:'Calculate averages for grades, numbers, and data sets with this free student calculator.',formula:'Average = sum of values / number of values.',inputs:['Values']},
  {slug:'fraction-to-percent-calculator',name:'Fraction to Percent Calculator',category:'Math Help',description:'Convert fractions into percentages.',title:'Fraction to Percent Calculator',meta:'Convert fractions to percentages quickly with this free calculator for students.',formula:'Percent = numerator / denominator × 100.',inputs:['Numerator','Denominator']},
  {slug:'percent-to-fraction-calculator',name:'Percent to Fraction Calculator',category:'Math Help',description:'Convert percentages into simplified fractions.',title:'Percent to Fraction Calculator',meta:'Convert percentages to fractions and simplify them for math homework.',formula:'Percent to fraction = percent / 100, then simplify.',inputs:['Percent']},
  {slug:'unit-rate-calculator',name:'Unit Rate Calculator',category:'Math Help',description:'Find the unit rate for math word problems.',title:'Unit Rate Calculator',meta:'Calculate unit rates for ratios, prices, speeds, and classroom word problems.',formula:'Unit rate = quantity / number of units.',inputs:['Quantity','Units']}
];

export const categories = Array.from(new Set(tools.map(t => t.category)));
export function getTool(slug: string){ return tools.find(t => t.slug === slug); }
export function relatedTools(slug: string, count = 6){
  const current = getTool(slug);
  const same = tools.filter(t => t.slug !== slug && t.category === current?.category);
  const other = tools.filter(t => t.slug !== slug && t.category !== current?.category);
  return [...same, ...other].slice(0, count);
}
